version: "3.10"

services:
  redis:
    image: redis:latest

  postgresql:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=students
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper:6.1.1
    ports:
      - 2181:2181
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000

  kafka:
    image: confluentinc/cp-kafka:latest
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://kafka:29092
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LOG_RETENTION_MS=86400000
    ports:
      - 9092:9092
      - 29092:29092
    depends_on:
      - zookeeper

  django:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - redis
      - postgresql
      - kafka

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A students worker -l info -E
    depends_on:
      - redis
      - postgresql
      - kafka

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A students beat -l info
    depends_on:
      - redis
      - postgresql
      - kafka

volumes:
  postgres_data:
