version: "3.10"

services:
  redis:
    image: redis:latest

  postgresql:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper:6.1.1
    ports:
      - 2181:2181
    environment:
      - ZOOKEEPER_CLIENT_PORT=${ZOOKEEPER_CLIENT_PORT}
      - ZOOKEEPER_TICK_TIME=${ZOOKEEPER_TICK_TIME}

  kafka:
    image: confluentinc/cp-kafka:latest
    environment:
      - KAFKA_ADVERTISED_LISTENERS=${KAFKA_ADVERTISED_LISTENER}
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP}
      - KAFKA_LISTENERS=${KAFKA_LISTENERS}
      - KAFKA_INTER_BROKER_LISTENER_NAME=${KAFKA_INTER_BROKER_LISTENER_NAME}
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR}
      - KAFKA_ZOOKEEPER_CONNECT=${KAFKA_ZOOKEEPER_CONNECT}
      - KAFKA_LOG_RETENTION_MS=${KAFKA_LOG_RETENTION_MS}

    ports:
      - 9092:9092
      - 29092:29092
    depends_on:
      - zookeeper

  django:
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - redis
      - postgresql
      - kafka

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A students worker -l info -E
    depends_on:
      - redis
      - postgresql
      - kafka

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A students beat -l info
    depends_on:
      - redis
      - postgresql
      - kafka

volumes:
  postgres_data:
